"""
handeye_calib.py — Interactive hand-eye calibration for the Unitree Z1 eye-in-hand setup.

Produces T_EE_cam.npz — the 4×4 homogeneous transform expressing the camera
frame in the EE (flange) frame.  Drop the file next to approach.py and you're done.

Workflow
--------
1.  Fix the ChArUco board rigidly in the scene — it must not move at all.
2.  Put the robot into gravity-compensation / teach mode.
3.  Physically move the arm to a pose where the board is fully visible.
4.  Press SPACE to capture (the border turns green when the board is detected).
5.  Repeat for at least 15 poses.  Vary wrist rotation heavily — small wrist
    rotations at different arm positions give the best conditioning.
6.  Press ENTER to run all five OpenCV solvers and save the best result.

Keys
----
  SPACE   capture current pose (board must be detected — green border)
  ENTER   run calibration and save  (requires ≥ MIN_CAPTURES poses)
  u       undo / remove last capture
  Esc     quit without saving

Requirements
------------
  pip install opencv-contrib-python numpy pylsl

Board parameters (must match gen_charuco_a4.py)
------
  5 × 7 squares, 35 mm squares, 26 mm markers, DICT_4X4_50
"""

import os
import sys
import glob
import time
import numpy as np
import cv2
from cv2 import aruco
from scipy.optimize import least_squares
import pylsl

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
SQUARES_X    = 5
SQUARES_Y    = 7
SQUARE_M     = 0.035        # metres
MARKER_M     = 0.026        # metres
DICT_ID      = aruco.DICT_4X4_50

MIN_CAPTURES            = 15    # refuse to calibrate below this
MIN_CORNERS             = 12    # minimum charuco corners for a valid pose (24 available on 5×7)
MAX_BOARD_REPROJ_PX     = 1.5   # reject board pose if solvePnP reprojection error exceeds this
PRUNE_THRESHOLD_MM      = 15.0  # drop pose pairs with per-pair error above this
MIN_PAIRS_AFTER_PRUNING = 12    # never prune below this count
CAMERA_INDEX = 0
OUTPUT_FILE  = "T_EE_cam.npz"

# Levenberg-Marquardt reprojection refinement after the AX=XB solve.
# LM minimises pixel reprojection error, which can trade away rotation
# consistency. Set False to save the raw AX=XB result (e.g. TSAI) directly.
USE_LM_REFINEMENT = True

# Folder (next to this script) where each capture is persisted as a .npz file.
# On re-run the existing captures are loaded automatically so you can keep adding.
CAPTURE_DIR  = os.path.join(os.path.dirname(os.path.abspath(__file__)), "handeye_data")

# ---------------------------------------------------------------------------
# Capture persistence
# ---------------------------------------------------------------------------
def _capture_files() -> list:
    """Return sorted list of capture .npz paths in CAPTURE_DIR."""
    return sorted(glob.glob(os.path.join(CAPTURE_DIR, "capture_*.npz")))


def _load_all_captures() -> tuple:
    """
    Load every saved capture from CAPTURE_DIR.
    Returns (T_base_EE_list, T_cam_board_list, obj_pts_list, img_pts_list, file_list).
    Bad/corrupt files are skipped with a warning.
    """
    files = _capture_files()
    T_EE, T_CB, OBJ, IMG, FL = [], [], [], [], []
    for f in files:
        try:
            d = np.load(f, allow_pickle=False)
            T_EE.append(d["T_base_EE"])
            T_CB.append(d["T_cam_board"])
            OBJ.append(d["obj_pts"])
            IMG.append(d["img_pts"])
            FL.append(f)
        except Exception as exc:
            print(f"[WARN] Skipping corrupt capture file {f}: {exc}")
    return T_EE, T_CB, OBJ, IMG, FL


def _save_capture(T_base_EE: np.ndarray, T_cam_board: np.ndarray,
                  obj_pts: np.ndarray, img_pts: np.ndarray) -> str:
    """
    Save one capture to CAPTURE_DIR/capture_NNNN.npz.
    The index is one higher than the current maximum so undo gaps are safe.
    Returns the saved filepath.
    """
    os.makedirs(CAPTURE_DIR, exist_ok=True)
    existing = _capture_files()
    if existing:
        last_idx = int(os.path.basename(existing[-1])
                       .replace("capture_", "").replace(".npz", ""))
        idx = last_idx + 1
    else:
        idx = 0
    path = os.path.join(CAPTURE_DIR, f"capture_{idx:04d}.npz")
    np.savez(path, T_base_EE=T_base_EE, T_cam_board=T_cam_board,
             obj_pts=obj_pts, img_pts=img_pts)
    return path


def _delete_capture(filepath: str):
    """Delete a saved capture file."""
    try:
        os.remove(filepath)
    except OSError as exc:
        print(f"[WARN] Could not delete {filepath}: {exc}")

# ---------------------------------------------------------------------------
# Camera intrinsics  (generated by your camera calibration step)
# ---------------------------------------------------------------------------
K    = np.load("camera_matrix.npy")
dist = np.load("dist_coeffs.npy")

# ---------------------------------------------------------------------------
# ChArUco board + detector  (OpenCV 4.7+ API)
# ---------------------------------------------------------------------------
_dict  = aruco.getPredefinedDictionary(DICT_ID)
board  = aruco.CharucoBoard((SQUARES_X, SQUARES_Y), SQUARE_M, MARKER_M, _dict)
_cdet  = aruco.CharucoDetector(board)

# ---------------------------------------------------------------------------
# LSL: connect to z1_pos  (avoids importing TransformManager whose
# constructor requires T_EE_cam.npz — the file we are about to create)
# ---------------------------------------------------------------------------
def _connect_lsl() -> pylsl.StreamInlet:
    print("Waiting for z1_pos LSL stream (up to 10 s)…")
    streams = pylsl.resolve_byprop("name", "z1_pos", minimum=1, timeout=10.0)
    if not streams:
        raise RuntimeError(
            "LSL stream 'z1_pos' not found after 10 s. "
            "Start the Z1 state publisher before running calibration."
        )
    inlet = pylsl.StreamInlet(streams[0])
    inlet.pull_sample(timeout=pylsl.FOREVER)   # blocking seed pull
    return inlet

_inlet:     pylsl.StreamInlet
_last_pose: np.ndarray

def _pull_pose() -> np.ndarray:
    global _last_pose
    sample, _ = _inlet.pull_sample(timeout=0.0)   # non-blocking
    if sample is not None:
        _last_pose = np.array(sample, dtype=np.float64)
    return _last_pose

def _pose_to_T(pose: np.ndarray) -> np.ndarray:
    """[roll, pitch, yaw, x, y, z] → 4×4 homogeneous matrix (ZYX Euler)."""
    roll, pitch, yaw = pose[0], pose[1], pose[2]
    x, y, z          = pose[3], pose[4], pose[5]
    cr, sr = np.cos(roll),  np.sin(roll)
    cp, sp = np.cos(pitch), np.sin(pitch)
    cy, sy = np.cos(yaw),   np.sin(yaw)
    Rx = np.array([[1, 0,  0 ], [0,  cr, -sr], [0, sr, cr]], np.float64)
    Ry = np.array([[cp, 0, sp], [0,   1,   0 ], [-sp, 0, cp]], np.float64)
    Rz = np.array([[cy, -sy, 0], [sy, cy, 0], [0, 0, 1]], np.float64)
    T = np.eye(4, dtype=np.float64)
    T[:3, :3] = Rz @ Ry @ Rx
    T[:3,  3] = [x, y, z]
    return T

# ---------------------------------------------------------------------------
# ChArUco pose detection  →  T_cam_board  (4×4)
# ---------------------------------------------------------------------------
def _detect_board(frame: np.ndarray):
    """
    Returns (T_cam_board, annotated_frame, n_corners, reproj_err_px, obj_pts, img_pts).
    T_cam_board is None if detection failed, not enough corners, or
    reprojection error exceeds MAX_BOARD_REPROJ_PX.
    obj_pts / img_pts are the matched 3-D / 2-D corner pairs (needed for LM refinement).
    """
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    ch_corners, ch_ids, _, _ = _cdet.detectBoard(gray)

    out = frame.copy()
    nc = 0 if ch_corners is None else len(ch_corners)

    if ch_corners is None or nc < MIN_CORNERS:
        return None, out, nc, None, None, None

    cv2.aruco.drawDetectedCornersCharuco(out, ch_corners, ch_ids, (0, 200, 255))

    obj_pts, img_pts = board.matchImagePoints(ch_corners, ch_ids)
    ok, rvec, tvec = cv2.solvePnP(
        obj_pts, img_pts, K, dist, flags=cv2.SOLVEPNP_ITERATIVE
    )
    if not ok:
        return None, out, nc, None, None, None

    proj_pts, _ = cv2.projectPoints(obj_pts, rvec, tvec, K, dist)
    reproj_err = float(np.mean(np.linalg.norm(
        img_pts.reshape(-1, 2) - proj_pts.reshape(-1, 2), axis=1
    )))

    if reproj_err > MAX_BOARD_REPROJ_PX:
        _put(out, f"Pose BAD: reproj={reproj_err:.1f}px (max {MAX_BOARD_REPROJ_PX}px) — tilt less",
             (10, 95), color=(0, 60, 255), scale=0.45)
        return None, out, nc, reproj_err, None, None

    cv2.drawFrameAxes(out, K, dist, rvec, tvec, SQUARE_M * 2)

    R, _ = cv2.Rodrigues(rvec)
    T = np.eye(4, dtype=np.float64)
    T[:3, :3] = R
    T[:3,  3] = tvec.flatten()
    return T, out, nc, reproj_err, obj_pts, img_pts

# ---------------------------------------------------------------------------
# Rotation diversity diagnostic
# ---------------------------------------------------------------------------
def _check_rotation_diversity(T_base_EE_list: list) -> float:
    """
    Print the spread of EE orientations across captured poses.
    Good hand-eye calibration needs mean pairwise angle > ~20°.
    Returns mean pairwise geodesic angle in degrees.
    """
    Rs = [T[:3, :3] for T in T_base_EE_list]
    n  = len(Rs)
    angles = []
    for i in range(n):
        for j in range(i + 1, n):
            diff    = Rs[i].T @ Rs[j]
            cos_val = np.clip((np.trace(diff) - 1.0) / 2.0, -1.0, 1.0)
            angles.append(np.degrees(np.arccos(cos_val)))
    mean_a = float(np.mean(angles))
    max_a  = float(np.max(angles))
    print(f"  EE rotation diversity:  mean={mean_a:.1f}°  max={max_a:.1f}°")
    if mean_a < 15.0:
        print("  [WARN] Very low rotation diversity — the wrist was barely rotated.")
        print("         Re-do: at each arm position, TILT the wrist in different directions.")
    elif mean_a < 25.0:
        print("  [INFO] Moderate rotation diversity — more wrist variation would help.")
    else:
        print("  [OK]   Rotation diversity looks sufficient.")
    return mean_a


# ---------------------------------------------------------------------------
# Outlier pruning for pose pairs
# ---------------------------------------------------------------------------
def _prune_pose_pairs(T_base_EE_list: list, T_cam_board_list: list,
                      T_EE_cam_init: np.ndarray):
    """
    Iteratively drop the pose pair with the highest per-pair board-position
    error until all remaining pairs are within PRUNE_THRESHOLD_MM, or
    MIN_PAIRS_AFTER_PRUNING pairs remain.
    Uses T_EE_cam_init (from the initial full calibration) for evaluation.
    Returns (kept_indices, removed_list_of_(global_idx, error_mm)).
    """
    indices = list(range(len(T_base_EE_list)))
    removed = []

    while True:
        sub_EE = [T_base_EE_list[i] for i in indices]
        sub_cb = [T_cam_board_list[i] for i in indices]

        positions = np.array(
            [(T_bEE @ T_EE_cam_init @ T_cb)[:3, 3]
             for T_bEE, T_cb in zip(sub_EE, sub_cb)]
        )
        mean_p = positions.mean(axis=0)
        errors = np.linalg.norm(positions - mean_p, axis=1) * 1000.0   # mm

        worst_local = int(np.argmax(errors))
        worst_err   = errors[worst_local]

        if worst_err <= PRUNE_THRESHOLD_MM:
            break
        if len(indices) <= MIN_PAIRS_AFTER_PRUNING:
            print(f"  [WARN] Stopped pruning at {len(indices)} pairs "
                  f"(floor={MIN_PAIRS_AFTER_PRUNING}). "
                  f"Worst remaining: {worst_err:.1f} mm.")
            break

        worst_global = indices[worst_local]
        removed.append((worst_global, worst_err))
        indices.pop(worst_local)
        print(f"  Pruned pair {worst_global + 1:>2}  "
              f"(error={worst_err:.1f} mm)  —  {len(indices)} remain")

    return indices, removed


# ---------------------------------------------------------------------------
# LM reprojection-error refinement
# ---------------------------------------------------------------------------
def _inv_T(T: np.ndarray) -> np.ndarray:
    """Efficient inversion of a 4×4 rigid-body transform."""
    R = T[:3, :3]
    t = T[:3,  3]
    Ti = np.eye(4, dtype=np.float64)
    Ti[:3, :3] = R.T
    Ti[:3,  3] = -R.T @ t
    return Ti


def _refine_with_reprojection(T_EE_cam_init: np.ndarray,
                               T_base_EE_list: list,
                               T_cam_board_list: list,
                               obj_pts_list: list,
                               img_pts_list: list) -> tuple:
    """
    Refine T_EE_cam using Levenberg-Marquardt reprojection-error minimisation.

    Jointly optimises T_EE_cam (6 DOF) and T_base_board (6 DOF) so that
    every captured board pose, projected through the current arm FK and
    the candidate T_EE_cam, minimises the sum of squared pixel errors.

    This is statistically optimal (maximum-likelihood under Gaussian noise)
    and avoids the error-propagation issue of AX=XB solvers that decouple
    rotation from translation.

    Returns (T_EE_cam_refined, reprojection_rms_px).
    """
    # ── Initial T_base_board estimate: mean position, orientation from pair 0 ──
    positions_init = np.array(
        [(T_bEE @ T_EE_cam_init @ T_cb)[:3, 3]
         for T_bEE, T_cb in zip(T_base_EE_list, T_cam_board_list)]
    )
    T_brd0 = T_base_EE_list[0] @ T_EE_cam_init @ T_cam_board_list[0]
    rv_brd0, _ = cv2.Rodrigues(T_brd0[:3, :3])
    tv_brd0    = positions_init.mean(axis=0)

    rv_cam0, _ = cv2.Rodrigues(T_EE_cam_init[:3, :3])
    tv_cam0    = T_EE_cam_init[:3, 3]

    # x = [rvec_cam(3), tvec_cam(3), rvec_board(3), tvec_board(3)]
    x0 = np.concatenate([rv_cam0.flatten(), tv_cam0,
                          rv_brd0.flatten(), tv_brd0])

    def residuals(x):
        R_cam, _ = cv2.Rodrigues(x[0:3])
        R_brd, _ = cv2.Rodrigues(x[6:9])

        T_cam = np.eye(4, dtype=np.float64)
        T_cam[:3, :3] = R_cam;  T_cam[:3, 3] = x[3:6]

        T_brd = np.eye(4, dtype=np.float64)
        T_brd[:3, :3] = R_brd;  T_brd[:3, 3] = x[9:12]

        res_all = []
        for T_bEE, obj_p, img_p in zip(T_base_EE_list, obj_pts_list, img_pts_list):
            T_cam_brd = _inv_T(T_bEE @ T_cam) @ T_brd
            rv, _  = cv2.Rodrigues(T_cam_brd[:3, :3])
            tv     = T_cam_brd[:3, 3]
            proj, _ = cv2.projectPoints(obj_p, rv, tv, K, dist)
            res_all.append((img_p.reshape(-1, 2) - proj.reshape(-1, 2)).flatten())
        return np.concatenate(res_all)

    result = least_squares(residuals, x0, method='lm', max_nfev=2000)

    R_ref, _ = cv2.Rodrigues(result.x[0:3])
    T_ref = np.eye(4, dtype=np.float64)
    T_ref[:3, :3] = R_ref
    T_ref[:3,  3] = result.x[3:6]

    final_res = residuals(result.x).reshape(-1, 2)
    rms_px = float(np.sqrt(np.mean(np.sum(final_res ** 2, axis=1))))

    return T_ref, rms_px


# ---------------------------------------------------------------------------
# Hand-eye calibration  — all five OpenCV solvers
# ---------------------------------------------------------------------------
_METHODS = {
    "TSAI":      cv2.CALIB_HAND_EYE_TSAI,
    "PARK":      cv2.CALIB_HAND_EYE_PARK,
    "HORAUD":    cv2.CALIB_HAND_EYE_HORAUD,
    "ANDREFF":   cv2.CALIB_HAND_EYE_ANDREFF,
    "DANIILIDIS": cv2.CALIB_HAND_EYE_DANIILIDIS,
}

def _make_T_EE_cam(R_c2g: np.ndarray, t_c2g: np.ndarray) -> np.ndarray:
    """Assemble T_EE_cam from calibrateHandEye output."""
    T = np.eye(4, dtype=np.float64)
    T[:3, :3] = R_c2g
    T[:3,  3] = t_c2g.flatten()
    return T

def _position_residual_mm(T_EE_cam: np.ndarray,
                           T_base_EE_list: list,
                           T_cam_board_list: list) -> float:
    """
    RMS of pairwise board-position disagreements in the base frame (mm).
    Lower is better.  A good calibration gives < 3 mm.
    """
    positions = []
    for T_bEE, T_cb in zip(T_base_EE_list, T_cam_board_list):
        T_base_board = T_bEE @ T_EE_cam @ T_cb
        positions.append(T_base_board[:3, 3])
    positions = np.array(positions)          # (N, 3)
    mean_pos  = positions.mean(axis=0)
    rms_mm    = np.sqrt(np.mean(np.sum((positions - mean_pos) ** 2, axis=1))) * 1000.0
    return rms_mm

def _rotation_residual_deg(T_EE_cam: np.ndarray,
                            T_base_EE_list: list,
                            T_cam_board_list: list) -> float:
    """Mean geodesic angle (deg) of board-rotation estimates around their mean."""
    Rs = []
    for T_bEE, T_cb in zip(T_base_EE_list, T_cam_board_list):
        Rs.append((T_bEE @ T_EE_cam @ T_cb)[:3, :3])

    # Approximate mean rotation via iterative averaging (one pass is fine here)
    R_mean = Rs[0].copy()
    for R in Rs[1:]:
        rv, _ = cv2.Rodrigues(R_mean.T @ R)
        R_mean = R_mean @ cv2.Rodrigues(rv * 0.5)[0]

    angles = []
    for R in Rs:
        diff = R_mean.T @ R
        cos_val = np.clip((np.trace(diff) - 1.0) / 2.0, -1.0, 1.0)
        angles.append(np.degrees(np.arccos(cos_val)))
    return float(np.mean(angles))

def _run_calibration(T_base_EE_list: list, T_cam_board_list: list):
    """
    Run all five solvers.  Print a comparison table.
    Return (best_name, best_T_EE_cam, pos_residual_mm, rot_residual_deg).
    """
    R_g2b = [T[:3, :3] for T in T_base_EE_list]
    t_g2b = [T[:3,  3].reshape(3, 1) for T in T_base_EE_list]
    R_t2c = [T[:3, :3] for T in T_cam_board_list]
    t_t2c = [T[:3,  3].reshape(3, 1) for T in T_cam_board_list]

    print(f"\n{'─'*60}")
    print(f"  {'Method':<12}  {'Pos RMS (mm)':>14}  {'Rot mean (deg)':>15}")
    print(f"  {'─'*12}  {'─'*14}  {'─'*15}")

    results = {}
    for name, method in _METHODS.items():
        try:
            R_c2g, t_c2g = cv2.calibrateHandEye(
                R_g2b, t_g2b, R_t2c, t_t2c, method=method
            )
            T = _make_T_EE_cam(R_c2g, t_c2g)
            pos_mm  = _position_residual_mm(T, T_base_EE_list, T_cam_board_list)
            rot_deg = _rotation_residual_deg(T, T_base_EE_list, T_cam_board_list)
            results[name] = (T, pos_mm, rot_deg)
            print(f"  {name:<12}  {pos_mm:>14.2f}  {rot_deg:>15.3f}")
        except Exception as exc:
            print(f"  {name:<12}  FAILED ({exc})")

    if not results:
        raise RuntimeError("All calibration methods failed.")

    best_name = min(results, key=lambda n: results[n][1])   # lowest pos RMS
    best_T, best_pos, best_rot = results[best_name]

    print(f"\n  Best: {best_name}  →  pos {best_pos:.2f} mm  |  rot {best_rot:.3f} deg")
    if best_pos > 5.0:
        print("  [WARN] Residual > 5 mm — consider re-doing with more varied poses.")
    print()
    return best_name, best_T, best_pos, best_rot

# ---------------------------------------------------------------------------
# Quality panel
# ---------------------------------------------------------------------------
def _draw_quality_panel(T_base_EE_list: list, T_cam_board_list: list,
                        T_EE_cam=None) -> np.ndarray:
    """
    Returns a 540×460 BGR image showing board-position consistency.
    Runs a fast TSAI preview if T_EE_cam is not yet available.
    Tight cluster = good calibration.  Target pos RMS < 3 mm.
    """
    W, H = 540, 460
    panel = np.full((H, W, 3), 28, dtype=np.uint8)

    N = len(T_base_EE_list)

    def pp(img, txt, pt, col=(210, 210, 210), sc=0.48, th=1):
        cv2.putText(img, txt, pt, cv2.FONT_HERSHEY_SIMPLEX, sc, (0,0,0), th+2, cv2.LINE_AA)
        cv2.putText(img, txt, pt, cv2.FONT_HERSHEY_SIMPLEX, sc, col,     th,   cv2.LINE_AA)

    pp(panel, "Board position consistency (top-down X-Y)", (10, 24),
       col=(230, 230, 230), sc=0.52)

    if N < 4:
        pp(panel, f"Capture >= 4 poses to see preview  ({N} so far)",
           (10, 60), col=(130, 130, 130))
        return panel

    # Quick TSAI solve for preview if final result not passed in
    T_use = T_EE_cam
    if T_use is None:
        try:
            R_g2b = [T[:3,:3] for T in T_base_EE_list]
            t_g2b = [T[:3,3].reshape(3,1) for T in T_base_EE_list]
            R_t2c = [T[:3,:3] for T in T_cam_board_list]
            t_t2c = [T[:3,3].reshape(3,1) for T in T_cam_board_list]
            Rc, tc = cv2.calibrateHandEye(R_g2b, t_g2b, R_t2c, t_t2c,
                                          method=cv2.CALIB_HAND_EYE_TSAI)
            T_use = np.eye(4, dtype=np.float64)
            T_use[:3,:3] = Rc;  T_use[:3,3] = tc.flatten()
        except Exception:
            pp(panel, "Preview unavailable — add more varied poses", (10, 60),
               col=(80, 80, 220))
            return panel

    # Board positions in base frame
    pts = []
    for T_bEE, T_cb in zip(T_base_EE_list, T_cam_board_list):
        p = (T_bEE @ T_use @ T_cb)[:3, 3]
        pts.append(p)
    pts = np.array(pts)                   # (N, 3)
    mean_p = pts.mean(axis=0)
    rms_mm = float(np.sqrt(np.mean(np.sum((pts - mean_p)**2, axis=1)))) * 1000.0

    # RMS colour
    if rms_mm < 3.0:
        rc = (60, 220, 60)
        grade = "GOOD"
    elif rms_mm < 8.0:
        rc = (40, 200, 230)
        grade = "OK"
    elif rms_mm < 20.0:
        rc = (40, 160, 255)
        grade = "POOR"
    else:
        rc = (60, 60, 230)
        grade = "BAD"

    label = "FINAL" if T_EE_cam is not None else "PREVIEW (TSAI)"
    pp(panel, f"Pos RMS: {rms_mm:.1f} mm  [{grade}]  {label}",
       (10, H - 14), col=rc, sc=0.52)
    pp(panel, "Target: < 3 mm", (W - 160, H - 14), col=(120, 120, 120), sc=0.40)

    # ── Scatter plot ─────────────────────────────────────────────────────
    MX, MY = 44, 44          # margin
    PW = W - 2 * MX
    PH = H - MY - 60         # leave room for title + footer

    xs = pts[:, 0] - mean_p[0]
    ys = pts[:, 1] - mean_p[1]

    # Scale so the largest deviation fills ~70 % of the plot
    max_dev = max(np.abs(xs).max(), np.abs(ys).max(), 0.005)
    scale = (min(PW, PH) * 0.35) / max_dev   # px per metre

    cx = MX + PW // 2
    cy = MY + 40 + PH // 2

    # Grid / axes
    cv2.rectangle(panel, (MX, MY + 40), (MX + PW, MY + 40 + PH), (55, 55, 55), 1)
    cv2.line(panel, (cx, MY + 40), (cx, MY + 40 + PH), (55, 55, 55), 1)
    cv2.line(panel, (MX, cy), (MX + PW, cy), (55, 55, 55), 1)

    # RMS circle
    rms_px = max(1, int(rms_mm / 1000.0 * scale))
    cv2.circle(panel, (cx, cy), rms_px, rc, 1, cv2.LINE_AA)

    # 3-mm target circle (if scale allows)
    target_px = int(0.003 * scale)
    if target_px > 2:
        cv2.circle(panel, (cx, cy), target_px, (60, 160, 60), 1, cv2.LINE_AA)
        pp(panel, "3mm", (cx + target_px + 2, cy - 4), col=(60, 160, 60), sc=0.35)

    # Data points: blue (first) → red (last)
    for i, (x, y) in enumerate(zip(xs, ys)):
        px = int(cx + x * scale)
        py = int(cy - y * scale)           # screen Y flipped
        t  = i / max(N - 1, 1)
        col = (int(255*(1-t)), 80, int(255*t))
        cv2.circle(panel, (px, py), 5, col, -1, cv2.LINE_AA)
        cv2.circle(panel, (px, py), 5, (200, 200, 200), 1, cv2.LINE_AA)

    # Mean cross
    cv2.drawMarker(panel, (cx, cy), (255, 255, 255),
                   cv2.MARKER_CROSS, 16, 2, cv2.LINE_AA)

    # Axis labels
    pp(panel, "X →", (MX + PW - 26, cy + 14), col=(140, 140, 140), sc=0.36)
    pp(panel, "↑Y",  (cx + 4, MY + 44),        col=(140, 140, 140), sc=0.36)
    pp(panel, f"±{max_dev*1000:.0f} mm",
       (MX + 2, MY + 44), col=(90, 90, 90), sc=0.36)

    # Capture index legend
    pp(panel, "● first", (MX, MY + 24), col=(255, 80, 0),  sc=0.38)
    pp(panel, "● last",  (MX + 70, MY + 24), col=(0, 80, 255), sc=0.38)

    return panel


# ---------------------------------------------------------------------------
# Overlay helpers
# ---------------------------------------------------------------------------
def _put(img, text, pt, color=(0, 220, 80), scale=0.50, thickness=1):
    cv2.putText(img, text, pt, cv2.FONT_HERSHEY_SIMPLEX, scale, (0,0,0), thickness+2, cv2.LINE_AA)
    cv2.putText(img, text, pt, cv2.FONT_HERSHEY_SIMPLEX, scale, color,   thickness,   cv2.LINE_AA)

def _draw_hud(frame, n_captures, board_ok, n_corners, reproj_err=None):
    h, w = frame.shape[:2]

    # Border: green = board good, yellow = board seen but pose bad, red = not detected
    border_col = (0, 200, 50) if board_ok else (0, 50, 220)
    cv2.rectangle(frame, (0, 0), (w - 1, h - 1), border_col, 4)

    # Status line
    if board_ok:
        status = f"Board OK  ({n_corners} corners)"
        col = (0, 200, 50)
    elif n_corners >= MIN_CORNERS and reproj_err is not None:
        status = f"Pose bad ({n_corners} corners, reproj={reproj_err:.1f}px) — face board more directly"
        col = (0, 150, 255)
    elif n_corners > 0:
        status = f"Too few corners: {n_corners} / {MIN_CORNERS} min — show more of the board"
        col = (0, 120, 255)
    else:
        status = "Board NOT DETECTED"
        col = (0, 80, 255)
    _put(frame, status, (10, 30), color=col)

    # Reprojection error when valid
    if board_ok and reproj_err is not None:
        err_col = (0, 200, 50) if reproj_err < 0.8 else (40, 180, 255)
        _put(frame, f"Reproj: {reproj_err:.2f} px", (10, 58), color=err_col)
        _put(frame, f"Captures: {n_captures} / {MIN_CAPTURES} min", (10, 84))
    else:
        _put(frame, f"Captures: {n_captures} / {MIN_CAPTURES} min", (10, 58))

    # Key hints
    hints = [
        "SPACE  capture  (green border + axes visible = ready)",
        f"ENTER  calibrate {'(ready)' if n_captures >= MIN_CAPTURES else f'(need {MIN_CAPTURES - n_captures} more)'}",
        "u      undo last    x  wipe all",
        "Esc    quit",
    ]
    for i, h_txt in enumerate(hints):
        _put(frame, h_txt, (10, h - 20 - (len(hints) - 1 - i) * 22),
             color=(200, 200, 200), scale=0.42)

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    global _inlet, _last_pose

    # Connect to robot
    _inlet = _connect_lsl()
    sample, _ = _inlet.pull_sample(timeout=5.0)
    if sample is None:
        raise RuntimeError("No pose sample received from z1_pos within 5 s.")
    _last_pose = np.array(sample, dtype=np.float64)
    print("Connected to z1_pos stream.")

    # Open camera. Resolution MUST match calibrate_camera.py (2K) or the loaded
    # intrinsics are for the wrong image size and every board pose is wrong.
    cap = cv2.VideoCapture(CAMERA_INDEX)
    cap.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc(*"MJPG"))  # 2K needs MJPEG over USB
    cap.set(cv2.CAP_PROP_FRAME_WIDTH,  2560)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 1440)
    if not cap.isOpened():
        raise RuntimeError(f"Cannot open camera index {CAMERA_INDEX}.")
    _aw = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    _ah = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    print(f"Camera opened at {_aw}×{_ah}")
    if (_aw, _ah) != (2560, 1440):
        print(f"[ABORT] Requested 2560×1440 but got {_aw}×{_ah}. Intrinsics won't "
              f"match — fix the camera 2K mode before calibrating.")
        cap.release()
        raise SystemExit(1)

    print(f"\nFix the ChArUco board in the scene and move the arm to diverse poses.")
    print(f"Press SPACE to capture, ENTER to calibrate (need ≥ {MIN_CAPTURES}), Esc to quit.\n")

    # ── Load previously saved captures ───────────────────────────────────
    T_base_EE_list, T_cam_board_list, obj_pts_list, img_pts_list, capture_files = \
        _load_all_captures()
    n_loaded = len(T_base_EE_list)
    if n_loaded:
        print(f"[+] Loaded {n_loaded} existing capture(s) from {CAPTURE_DIR}")
        print(f"    Press 'X' to wipe all saved captures and start fresh.\n")
    else:
        print(f"[INFO] No existing captures found in {CAPTURE_DIR}  (starting fresh)\n")

    while True:
        ret, frame = cap.read()
        if not ret:
            print("[WARN] Camera read failed — retrying…")
            continue

        T_cam_board, annotated, n_corners, reproj_err, obj_pts, img_pts = _detect_board(frame)
        board_ok = T_cam_board is not None
        _draw_hud(annotated, len(T_base_EE_list), board_ok, n_corners, reproj_err)

        cv2.imshow("Hand-Eye Calibration", annotated)
        key = cv2.waitKey(1) & 0xFF

        # ── SPACE: capture ────────────────────────────────────────────────
        if key == ord(' '):
            if not board_ok:
                print("[SKIP] Board not detected — move arm so the full board is visible.")
                continue
            # Flush stale samples then wait for arm to settle
            while _inlet.pull_sample(timeout=0.0)[0] is not None:
                pass
            time.sleep(0.6)   # let the arm finish settling
            # Verify arm is still (position must not drift > 1 mm over 0.2 s)
            s1, _ = _inlet.pull_sample(timeout=0.5)
            time.sleep(0.2)
            s2, _ = _inlet.pull_sample(timeout=0.5)
            if s1 is None or s2 is None:
                print("[SKIP] Could not read pose — is z1_pos streaming?")
                continue
            p1 = np.array(s1[3:6])
            p2 = np.array(s2[3:6])
            drift_mm = np.linalg.norm(p2 - p1) * 1000.0
            if drift_mm > 1.0:
                print(f"[SKIP] Arm still moving ({drift_mm:.1f} mm drift) — hold still longer.")
                continue
            pose  = np.array(s2, dtype=np.float64)
            T_bEE = _pose_to_T(pose)
            T_base_EE_list.append(T_bEE)
            T_cam_board_list.append(T_cam_board)
            obj_pts_list.append(obj_pts)
            img_pts_list.append(img_pts)
            saved_path = _save_capture(T_bEE, T_cam_board, obj_pts, img_pts)
            capture_files.append(saved_path)
            n = len(T_base_EE_list)
            xyz  = T_bEE[:3, 3]
            print(f"[+] Capture {n:>2}  EE=({xyz[0]:.3f}, {xyz[1]:.3f}, {xyz[2]:.3f}) m"
                  f"  corners={n_corners}"
                  f"  reproj={reproj_err:.2f}px"
                  f"  drift={drift_mm:.2f}mm"
                  f"  → {os.path.basename(saved_path)}")
            cv2.imshow("Quality", _draw_quality_panel(T_base_EE_list, T_cam_board_list))

        # ── u: undo ───────────────────────────────────────────────────────
        elif key == ord('u'):
            if T_base_EE_list:
                T_base_EE_list.pop()
                T_cam_board_list.pop()
                obj_pts_list.pop()
                img_pts_list.pop()
                if capture_files:
                    _delete_capture(capture_files.pop())
                print(f"[-] Removed last capture.  {len(T_base_EE_list)} remaining.")
            else:
                print("[INFO] Nothing to undo.")

        # ── ENTER: calibrate ──────────────────────────────────────────────
        elif key == 13:
            n = len(T_base_EE_list)
            if n < MIN_CAPTURES:
                print(f"[SKIP] Need at least {MIN_CAPTURES} captures, have {n}.")
                continue

            print(f"\nRunning hand-eye calibration on {n} pose pairs…")
            _check_rotation_diversity(T_base_EE_list)

            try:
                best_name, T_EE_cam, pos_mm, rot_deg = _run_calibration(
                    T_base_EE_list, T_cam_board_list
                )
            except RuntimeError as exc:
                print(f"[ERROR] Calibration failed: {exc}")
                continue

            # ── Outlier pruning ───────────────────────────────────────────
            print(f"\nPruning outlier pose pairs  (threshold={PRUNE_THRESHOLD_MM} mm):")
            kept, removed_pairs = _prune_pose_pairs(
                T_base_EE_list, T_cam_board_list, T_EE_cam
            )
            if removed_pairs:
                print(f"\n  Removed {len(removed_pairs)} pair(s). "
                      f"Re-running calibration on {len(kept)} pairs…")
                sub_EE = [T_base_EE_list[i] for i in kept]
                sub_cb = [T_cam_board_list[i] for i in kept]
                try:
                    best_name, T_EE_cam, pos_mm, rot_deg = _run_calibration(
                        sub_EE, sub_cb
                    )
                except RuntimeError as exc:
                    print(f"[ERROR] Re-calibration failed: {exc}")
                    continue
            else:
                print(f"  No pairs removed — all within {PRUNE_THRESHOLD_MM} mm.")

            final_EE  = [T_base_EE_list[i] for i in kept]
            final_cb  = [T_cam_board_list[i] for i in kept]
            final_obj = [obj_pts_list[i]    for i in kept]
            final_img = [img_pts_list[i]    for i in kept]

            # ── LM reprojection-error refinement (optional) ───────────────
            if not USE_LM_REFINEMENT:
                print(f"\nLM refinement disabled — saving raw {best_name} (AX=XB) result.")
            else:
                print(f"\nRefining with Levenberg-Marquardt reprojection optimisation…")
                try:
                    T_EE_cam_lm, reproj_rms = _refine_with_reprojection(
                        T_EE_cam, final_EE, final_cb, final_obj, final_img
                    )
                    pos_mm_lm  = _position_residual_mm(T_EE_cam_lm, final_EE, final_cb)
                    rot_deg_lm = _rotation_residual_deg(T_EE_cam_lm, final_EE, final_cb)
                    print(f"  Reprojection RMS  : {reproj_rms:.3f} px")
                    print(f"  Position residual : {pos_mm_lm:.2f} mm  (AX=XB was {pos_mm:.2f} mm)")
                    print(f"  Rotation residual : {rot_deg_lm:.3f} deg  (AX=XB was {rot_deg:.3f} deg)")
                    # Accept only if BOTH position and rotation do not worsen.
                    if pos_mm_lm <= pos_mm * 1.05 and rot_deg_lm <= rot_deg * 1.05:
                        T_EE_cam = T_EE_cam_lm
                        pos_mm   = pos_mm_lm
                        rot_deg  = rot_deg_lm
                    else:
                        print("  [WARN] LM worsened pos or rot — keeping AX=XB result.")
                except Exception as exc:
                    print(f"  [WARN] LM refinement failed ({exc}) — keeping AX=XB result.")

            np.savez(OUTPUT_FILE, T_EE_cam=T_EE_cam)
            print(f"\nSaved {OUTPUT_FILE}  (method: {best_name})")
            print(f"  Pairs used        : {len(kept)} / {n}")
            print(f"  Position residual : {pos_mm:.2f} mm")
            print(f"  Rotation residual : {rot_deg:.3f} deg")
            print(f"\nT_EE_cam =\n{T_EE_cam}\n")
            cv2.imshow("Quality", _draw_quality_panel(final_EE, final_cb, T_EE_cam))
            print("Press any key in the Quality window to exit.")
            cv2.waitKey(0)
            break

        # ── x: wipe all captures and start fresh ─────────────────────────
        elif key == ord('x'):
            print(f"\nWipe ALL {len(T_base_EE_list)} capture(s) from {CAPTURE_DIR}? "
                  f"Type 'yes' in terminal and press Enter to confirm, or anything else to cancel.")
            confirm = input("> ").strip().lower()
            if confirm == "yes":
                for f in capture_files:
                    _delete_capture(f)
                T_base_EE_list.clear()
                T_cam_board_list.clear()
                obj_pts_list.clear()
                img_pts_list.clear()
                capture_files.clear()
                n_loaded = 0
                print("[X] All captures deleted.  Starting fresh.")
            else:
                print("[CANCEL] Wipe cancelled.")

        # ── Esc: quit ─────────────────────────────────────────────────────
        elif key == 27:
            print("Quit — no file saved.")
            break

    cap.release()
    cv2.destroyAllWindows()


if __name__ == "__main__":
    main()
